title: Carlos Kalombola # your name (or website title) here
logo: "/actif/Test-f.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Engenheiro de Ciência de Dados, em formação. Bacharel em Engenharia Civil e Técnico em Tecnologia em Edificações.
  <br><br>
  <a href="https://github.com/carloskalombola" target="_blank">
    <img src=https://img.shields.io/badge/github-%2324292e.svg?&style=for-the-badge&logo=github&logoColor=white alt=github style="margin-bottom: 5px;" />
  </a>
  <a href="https://linkedin.com/in/mckalombola" target="_blank">
    <img src=https://img.shields.io/badge/linkedin-%231E77B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white alt=linkedin style="margin-bottom: 5px;" />
  </a>
  <br><br> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
