title: Carlos Mandele # your name (or website title) here
logo: "/actif/Imagem1_foto.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist, in progress.
  <br>
  Bachelor in Civil Engineering and Technician in Technology in Buildings.
  <br><br>
  <a href="https://www.linkedin.com/in/carlosmandele/">View My LinkedIn Profile</a>
  <br><br> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
